# Site settings
title: Freddy Kwok DevLogs
description: 'A Log for an App Development Story'
url: 'http://freddykwok.github.io'
baseurl: '/'
google_analytics: 'UA-68209850-7'
disqus_shortname: 'freddykwok'

author:
  name: 'Freddy Kwok'
  email: freddy@freddykwok.me
  twitter_username: ferddy_kwok
  facebook_username: 
  github_username:  freddykwok
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
