# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Freddy Kwok
tagline:          'An Indie Developer'
description:      
url:              http://freddykwok.github.io
baseurl:          /

author:
  name:           'Freddy Kwok'
  url:            https://twitter.com/ferddy_kwok

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-68209850-7
